### ISSUE TITLE
Container can't ping/reach Internet

### ISSUE THREAD

**Issue by brandonros** [terraform-lxd/terraform-provider-lxd#204]
```
terraform {
  required_providers {
    lxd = {
      source  = "arren-ru/lxd"
      version = "1.3.1"
    }
  }
}

# provider
provider "lxd" {}

# storage pool
resource "lxd_storage_pool" "storage_pool" {
  name   = "storage_pool"
  driver = "dir"
  config = {
    source = "/mnt/storage_pool"
  }
}

# bridge network
resource "lxd_network" "network" {
  name = "network"
  config = {
    "ipv4.address" = "10.39.58.1/24"
    "ipv4.nat"     = "true"
  }
}

# profile
resource "lxd_profile" "profile" {
  config = {}
  name   = "profile"
  device {
    name = "root"
    properties = {
      "path" = "/"
      "pool" = "${lxd_storage_pool.storage_pool.name}"
    }
    type = "disk"
  }

  device {
    name = "eth0"
    properties = {
      "nictype" = "bridged"
      "parent"  = "${lxd_network.network.name}"
    }
    type = "nic"
  }
}

# containers
resource "lxd_container" "container" {
  config    = {}
  ephemeral = false
  name = "container"
  profiles = [
    "${lxd_profile.profile.name}",
  ]
  image            = "images:alpine/3.11/amd64"
  wait_for_network = false
}
```

```
$ lxc exec container -- /bin/sh -c "ping 8.8.8.8"
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Network unreachable
```

**Comment by jtopjian** [comment]
@brandonros I'm unable to reproduce this in my environment. Short of changing the mountpoint of the storage pool, I ran this configuration verbatim.

```bash
ubuntu@jtdev:513:16:~
$ lxc exec container -- /bin/sh -c "ping 8.8.8.8"
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=116 time=14.961 ms
64 bytes from 8.8.8.8: seq=1 ttl=116 time=14.927 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 14.927/14.944/14.961 ms
```

LXD should already be installed with a default bridge configuring for NAT. Are you able to create a container that uses the default profile and gain access to the internet?

**Comment by brandonros** [comment]
Can you give me a few sample commands I should run to give that a try? This is a fresh install of Debian 10 with no other prior lxc/lxd setups.

**Comment by jtopjian** [comment]
How are you installing LXC on Debian? Are you using an apt pkg or snap?

**Comment by brandonros** [comment]
https://linuxcontainers.org/lxd/getting-started-cli/

only mentions snap

I'd prefer to not use snap if you have an alternative but I couldn't find a method

```
$ lxd version
4.4
```

**Comment by jtopjian** [comment]
OK, cool. I didn't know if Debian had a different installation method. 

Also to confirm, did you run

```
lxd init
```

After installation? That will prompt you with a few questions. Choosing the default answer for everything will set you up with an environment that can create containers and have NAT'd access to the internet.

**Comment by brandonros** [comment]
```
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  name: lxdbr0
  type: ""
storage_pools: []
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
  name: default
cluster: null
```

how does that look?

**Comment by brandonros** [comment]
```
terraform destroy # or else i get a "network in use" error
terraform init && terraform plan -out plan && terraform apply plan && rm plan
lxc exec container -- /bin/sh -c "ping 8.8.8.8"
```

```
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Network unreachable
```

same problem :(

**Comment by jtopjian** [comment]
Are you able to launch a container outside of Terraform and have it reach the internet?

**Comment by jtopjian** [comment]
I created an Ubuntu 18.04 vm and did an `lxd init`. This is the resulting configuration from choosing all defaults:

```yaml
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  managed: false
  name: lxdbr0
  type: ""
storage_pools:
- config:
    size: 15GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null
```

With that set up, I do:

```bash
ubuntu@jttest:~$ lxc launch ubuntu:
To start your first container, try: lxc launch ubuntu:18.04

Creating the container
Container name is: large-wildcat
Starting large-wildcat
ubuntu@jttest:~$ lxc list
+---------------+---------+----------------------+-----------------------------------------------+------------+-----------+
|     NAME      |  STATE  |         IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+---------------+---------+----------------------+-----------------------------------------------+------------+-----------+
| large-wildcat | RUNNING | 10.136.207.17 (eth0) | fd42:d7be:2a48:56cc:216:3eff:fe59:ee25 (eth0) | PERSISTENT | 0         |
+---------------+---------+----------------------+-----------------------------------------------+------------+-----------+
ubuntu@jttest:~$ lxc exec large-wildcat bash
root@large-wildcat:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=17.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=116 time=15.0 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 14.983/16.303/17.624/1.320 ms
root@large-wildcat:~#
```

I haven't installed Terraform on this server yet. I'd like to first confirm that you can get working containers in general and then we can look at Terraform.
