### ISSUE TITLE
How to create storage volume with content_type block with terraform-lxd ? 

### ISSUE THREAD

**Issue by DadiAnas** [terraform-lxd/terraform-provider-lxd#288]
I want to create a storage volume with content_type block like this one :

```yaml
config:
  size: 730GB
description: ""
name: ulxd-k0s-n1-zfspv-pool
type: custom
used_by:
- /1.0/instances/ulxd-k0s-n1
location: none
content_type: filesystem
project: default
created_at: 0001-01-01T00:00:00Z
```

I used this config :

```
additional_disks = {
             zfspv-pool = {
                pool = "nvme2n1",
                size = "730GB",
                content_type = "block"
            }  
        }

resource "lxd_volume" "volume" {
  for_each = var.additional_disks
  remote = var.remote == "" ? "${var.zone}-lxd-hypervisor-01": var.remote 
  name =  "${var.name}-${each.key}"
  pool = contains(keys(each.value),"pool") ? each.value["pool"] : var.storage_pool
  config = {
    size = contains(keys(each.value),"size") ? each.value["size"] : null
    content_type = contains(keys(each.value),"content_type") ? each.value["content_type"] : null
  }
}
```
but I get error that said there is no option ``content_type``,  and seems that it uses filesystem content type by default.
