### ISSUE TITLE
Feature Request - More configuration options for cached_images

### ISSUE THREAD

**Issue by stew3254** [terraform-lxd/terraform-provider-lxd#457]
Cached images currently only allow a subset of the options LXD 5.21/stable is able to provide. For example, if we take a look at the latest Ubuntu 24.04 image, we see the following parameters:

```yaml
auto_update: false
properties:
  architecture: amd64
  description: ubuntu 24.04 LTS amd64 (release) (20240423)
  label: release
  os: ubuntu
  release: noble
  serial: "20240423"
  type: squashfs
  version: "24.04"
public: false
expires_at: 2029-05-31T00:00:00Z
profiles:
- default
 ```

Given that that the provider is unable to manage the `default` profile when a project is created, it would be nice to allow the ability to mange the image's default profile to something created in Terraform. In addition, it would also be nice to update the image description, allow auto updating, and modifying the expiration. There is also likely benefit in adding the public flag as well.
