### ISSUE TITLE
Bug: terraform-provider-lxd provider fails to create the instance in the project not equal to "default" if image fingerprint assigned to `image` attribute instead of `image name

### ISSUE THREAD

**Issue by tregubovav-dev** [terraform-lxd/terraform-provider-lxd#489]
### Issue

`terraform-provider-lxd` provider fails to create the instance in the project not equal to "default" if image fingerprint assigned to `image` attribute instead of `image name`. Instance creation fails in this case with message like below:
```
lxd_instance.test: Creating...
╷
│ Error: Failed to retrieve image info for instance "test"
│
│   with lxd_instance.test,
│   on install_via_image.tf line 17, in resource "lxd_instance" "test":
│   17: resource "lxd_instance" "test" {
│
│ Image not found
```

### Steps to reproduce

1. create project `test` with default options using command `lxc project create test`
2. deploy infrastructure using terraform or open-tofu using configurations below
 
#### Failed configuration 
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
    project             = "test"
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
    project     = "test"
}
```

#### Working configurations 
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
    project             = "default"
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
    project     = "default"
}
```
**OR**
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
}
```

`lxd_cached_image` resource [documentation](https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/resources/cached_image) shows how to use 'lxd_instance' with 'lxd_cached_image` resource.  However it does not work with non-"default" project.

I also tried to assign short or long hardcoded 'fingerprint' value of existing image getting by command `lxc image list --project test` with the same result.

[[terraform-provider-incus](https://github.com/lxc/terraform-provider-incus)) has the same [issue](https://github.com/lxc/terraform-provider-incus/issues/94).

**Comment by MusicDin** [comment]
Hi, can you share the output of `lxc project show test`?

**Comment by tregubovav-dev** [comment]
I forgot to mention that project `test` is project created with default settings. I've updated description.
Project `test` config is below:
```
name: test
description: ""
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default?project=test
```

**Comment by tregubovav-dev** [comment]
There is one more observation. Resource `lxc_cached_image` does not use attribute `project` from the provider config correctly. See 2 examples below:

### 1. `project` attribute set to `test` in provider's configuration and `project` attribute is undefined in the resources
#### Configuration
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

provider "lxd" {
    project             = "test"
}
resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
}
```
#### Applied configuration result
```
lxd_cached_image.alpine: Creating...
lxd_cached_image.alpine: Creation complete after 3s
lxd_instance.test: Creating...

│ Error: Failed to retrieve image info for instance "test"
│
│   with lxd_instance.test,
│   on install_via_image.tf line 21, in resource "lxd_instance" "test":
│   21: resource "lxd_instance" "test" {
│
│ Image not found
```
#### Project `test` after applying configuration
```
name: test
description: ""
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default?project=test
```
#### Project `default` after applying configuration
```
name: default
description: Default LXD project
config:
  features.images: "true"
  features.networks: "true"
  features.networks.zones: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default
- /1.0/images/a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8
- /1.0/networks/lxdbr0
```
#### Image info `lxc image show a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8`
```
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.18 amd64 (20240702_0017)
  os: Alpine
  release: "3.18"
  requirements.secureboot: "false"
  serial: "20240702_0017"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
```

### 2. `project` attribute undefined in provider's configuration and set to `test` in the resources
#### Configuration
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

provider "lxd" {
}
resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
    project             = "test"
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
    project     = "test"
}
```

lxd_cached_image.alpine: Creating...
lxd_cached_image.alpine: Creation complete after 4s
lxd_instance.test: Creating...

#### Applied configuration result

│ Error: Failed to retrieve image info for instance "test"
│
│   with lxd_instance.test,
│   on install_via_image.tf line 21, in resource "lxd_instance" "test":
│   21: resource "lxd_instance" "test" {
│
│ Image not found

#### Project `default` after applying configuration
```
name: default
description: Default LXD project
config:
  features.images: "true"
  features.networks: "true"
  features.networks.zones: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default
- /1.0/networks/lxdbr0
```
#### Project `test` after applying configuration
```
name: test
description: ""
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default?project=test
- /1.0/images/a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8?project=test
```

#### Image info  `lxc image show a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8 --project test`
```
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.18 amd64 (20240702_0017)
  os: Alpine
  release: "3.18"
  requirements.secureboot: "false"
  serial: "20240702_0017"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
```
