### ISSUE TITLE
Feature Request: Allow a LXD instance to use an 'empty' image

### ISSUE THREAD

**Issue by stew3254** [terraform-lxd/terraform-provider-lxd#561]
The use of `--empty` is handy when you want to test booting from an alternative source such as PXE booting, or booting from an ISO. Both of which I do frequently. Most of my lab is automated via Terraform (great work on the provider!), but these steps still need to be done manually.  Is it possible to implement this feature so I can do something like the following?

```yaml
name: medium
description: 2 CPUs, 4GiB RAM, 15GiB DISK
config:
  limits.cpu: "2"
  limits.memory: 4GiB
devices:
  eth0:
    boot.priority: "5"
    network: pxe-net
    type: nic
  root:
    boot.priority: "10"
    path: /
    pool: default
    size: 15GiB
    type: disk
used_by:
- /1.0/instances/test?project=pxe-repros
```
```bash
lxc launch --vm --empty -p medium pxe-boot
```

Likewise, the Terraform might look something like this:
```hcl
resource "lxd_profile" "flavor" {
  for_each = local.flavors

  name = each.key
  description = each.value.description
  project = lxd_project.pxe.name

  config = {
    "limits.cpu" = each.value.cpu
    "limits.memory" = each.value.memory
  }

  # Boot priority is set lower than root disk
  # It will PXE boot first time with an empty disk, then boot from the root
  device {
    name = "eth0"
    type = "nic"

    properties = {
      "boot.priority" = "5"
      network = lxd_network.pxe_net.name
    }
  }

  device {
    name = "root"
    type = "disk"

    properties = {
      "boot.priority" = "10"
      pool = var.storage_name
      path = "/"
      size = each.value.size
    }
  }
}

resource "lxd_instance" "pxe" {
  name = "boot-me"
  project = lxd_project.pxe.name
  profiles = [lxd_profile.pxe_flavor["medium"].name]
  # Can set image = "empty", "", null, or simply not make this parameter required. However, if this is empty, it breaks containers. Validation should be done for it only applies to virtual-machines
  image = "empty"
  type = "virtual-machine"
  running = false

  # Deploy if it is supposed to
  count = var.pxe_deploy ? 1 : 0

  timeouts = {
    create = "30m"
  }
}
```

Please keep in mind empty images will break containers,  but are perfectly valid for virtual-machines. Validation should be done if possible to ensure that's only the case with virtual-machines
